DECLARE @UNEM_ID VARCHAR(22)

SET @UNEM_ID = ':id_company'

SELECT
	@UNEM_ID AS 'id_company', PROD.PROD_ID AS 'id', PROD.PROD_CODIGO AS 'code',
	PROD.PROD_NOME AS 'name', ISNULL(SDES.SEST_QTD_REAL,0) AS 'balance'
FROM
	PRODUTOS PROD
LEFT JOIN
	vw_SALDO_ESTOQUE SDES
	ON PROD.PROD_ID = SDES.PROD_ID AND
	SDES.SBUP_TIPO = 'Padrão' AND
	SDES.TEST_ID LIKE @UNEM_ID+'%'
WHERE
	PROD.PROD_SITUACAO = 'Ativo' AND
	PROD.PROD_CODIGO = '6329'