DECLARE @UNEM_ID VARCHAR(22)
DECLARE @PROD_ID VARCHAR(22)
DECLARE @DATE_AUX DATE

DECLARE @WEEKS TABLE (START_WEEK DATE, END_WEEK DATE)

--SET @UNEM_ID = ':id_company'
--SET @PROD_ID = ':id_product'

SET @UNEM_ID = '001410060005'
SET @PROD_ID = '001410060000002201'

SET @DATE_AUX = DATEADD(YEAR, -2, GETDATE())
INSERT INTO @WEEKS(START_WEEK, END_WEEK) VALUES(@DATE_AUX, DATEADD(DAY, 7, @DATE_AUX))

WHILE (SELECT MAX(END_WEEK) FROM @WEEKS) < GETDATE()
BEGIN
	SET @DATE_AUX = DATEADD(DAY,1,(SELECT MAX(END_WEEK) FROM @WEEKS))
	INSERT INTO @WEEKS(START_WEEK, END_WEEK) VALUES(@DATE_AUX, DATEADD(DAY, 7, @DATE_AUX))
END
--SELECT * FROM @WEEKS
  
SELECT
   WEEKS.START_WEEK AS 'start_week', WEEKS.END_WEEK AS 'end_week',
   COUNT(ISNULL(DCFS.DCFS_ID,0)) AS 'sales', SUM(ISNULL(DCFS.ITFT_QTDE_FATURADA,0)) AS 'quantity'
FROM
   @WEEKS WEEKS
LEFT JOIN
   (SELECT
      DCFS1.DCFS_DATA_SAIDA, DCFS1.DCFS_ID, ITFT.ITFT_QTDE_FATURADA
   FROM
      DOCUMENTOS_FISCAIS DCFS1
   LEFT JOIN
      ITENS_FATURADOS ITFT
      ON DCFS1.DCFS_ID = ITFT.DCFS_ID
   WHERE
      ITFT.PROD_ID = @PROD_ID AND
      DCFS1.DCFS_ID LIKE @UNEM_ID + '%' AND   
      DCFS1.DCFS_STATUS = 'Válido' AND
      DCFS1.DCFS_TIPO_MOVIMENTO = 'Saída' AND
      DCFS1.DCFS_NATUREZA_OPERACAO = 'Venda') DCFS
   ON DCFS.DCFS_DATA_SAIDA BETWEEN dbo.FN_ONLYDATE(WEEKS.START_WEEK) AND dbo.FN_ULTIMAHORA(WEEKS.END_WEEK)   
GROUP BY
   WEEKS.START_WEEK, WEEKS.END_WEEK	   
ORDER BY
   WEEKS.START_WEEK